# Generated by Django 4.1.5 on 2023-01-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todogym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='pesos',
            new_name='weights',
        ),
    ]
