# Generated by Django 4.1.5 on 2023-01-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todogym', '0002_rename_pesos_todo_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='series',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='weights',
            field=models.CharField(max_length=500),
        ),
    ]
